---
title: Bathaya
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Blog perso d'un designer en transition
baseurl: '/bathaya'
url: 'https://batgithub.github.io'
github_username: batgithub
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
