---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
collections: 
upload_dir: assets/posts
public_path: assets/posts
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
